HTML = r'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AgentNode 3.2</title>
<style>:root{color-scheme:dark;--bg:#080d18;--card:#0f182c;--line:#22304d;--muted:#91a0be;--accent:#77a8ff}*{box-sizing:border-box}body{font:14px ui-sans-serif,system-ui;margin:0;background:var(--bg);color:#e8edf7}header{position:sticky;top:0;z-index:2;padding:14px 20px;background:#0e1730ee;backdrop-filter:blur(12px);border-bottom:1px solid #263456}.brand{font-size:18px;font-weight:800}.muted{color:var(--muted)}.bar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:8px}input,button,select,textarea{padding:9px 11px;border-radius:8px;background:#141f3c;color:#fff;border:1px solid #33476f}button{cursor:pointer}button:hover{background:#1c2a50}main{padding:18px;max-width:1700px;margin:auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.card{background:var(--card);border:1px solid #1e2d4b;padding:14px;border-radius:12px;box-shadow:0 8px 28px #0003}.metric{font-size:26px;font-weight:800}.green{color:#64d98b}.red{color:#ff7b7b}.tabs{display:flex;gap:6px;flex-wrap:wrap;margin:14px 0}.tabs button.active{background:#285cb8}.panel{display:none}.panel.active{display:block}.split{display:grid;grid-template-columns:minmax(420px,1.4fr) minmax(340px,1fr);gap:12px}@media(max-width:900px){.split{grid-template-columns:1fr}}pre{white-space:pre-wrap;word-break:break-word;max-height:540px;overflow:auto;background:#090f1d;padding:12px;border-radius:8px}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid var(--line);text-align:left}tr:hover{background:#16213b;cursor:pointer}.pill{padding:3px 7px;border-radius:999px;background:#25314c;font-size:12px}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.grow{flex:1;min-width:260px}</style></head>
<body><header><div class="brand">AgentNode 3.2 <span class="muted">Documents + CDP + Office COM + Unified Desktop Graph</span></div><div class="bar"><input id="token" type="password" size="42" placeholder="Bearer token"><button onclick="connect()">Connect</button><span id="status" class="muted">disconnected</span></div></header>
<main><div class="grid"><div class="card"><div class="muted">Node</div><div id="nodeName" class="metric">—</div><div id="nodeMeta" class="muted"></div></div><div class="card"><div class="muted">Running jobs</div><div id="running" class="metric">0</div></div><div class="card"><div class="muted">Terminal sessions</div><div id="termCount" class="metric">0</div></div><div class="card"><div class="muted">Search sessions</div><div id="searchCount" class="metric">0</div></div><div class="card"><div class="muted">Peers</div><div id="peerCount" class="metric">0</div></div><div class="card"><div class="muted">Tool calls</div><div id="toolCalls" class="metric">0</div></div></div>
<div class="tabs"><button class="active" onclick="tab('jobs',this)">Jobs</button><button onclick="tab('terminal',this)">Terminal</button><button onclick="tab('search',this)">Search</button><button onclick="tab('files',this)">Files</button><button onclick="tab('history',this)">History</button><button onclick="tab('config',this)">Config</button><button onclick="tab('desktop',this)">Desktop Graph</button><button onclick="tab('browser',this)">Browser</button><button onclick="tab('documents',this)">Documents</button><button onclick="tab('runtime',this)">Runtime</button></div>
<section id="jobs" class="panel active"><div class="split"><div class="card"><h3>Tasks / history</h3><table><thead><tr><th>State</th><th>Kind</th><th>Progress</th><th>Owner</th><th>Job</th></tr></thead><tbody id="jobRows"></tbody></table></div><div class="card"><h3>Selected job</h3><div class="bar"><input id="jid" class="grow" placeholder="job id"><button onclick="inspectJob()">Inspect</button><button onclick="cancelJob()">Cancel</button></div><pre id="jobDetail">Select a job.</pre><h4>Events / stdout / stderr</h4><pre id="events">—</pre></div></div></section>
<section id="terminal" class="panel"><div class="split"><div class="card"><h3>Terminal sessions</h3><button onclick="loadTerms()">Refresh</button><pre id="terms">—</pre></div><div class="card"><h3>Read session</h3><div class="bar"><input id="sid" class="grow" placeholder="session id"><input id="tcursor" size="8" value="0"><button onclick="readTerm()">Read</button></div><pre id="termOut">—</pre></div></div></section>
<section id="search" class="panel"><div class="split"><div class="card"><h3>Search sessions</h3><button onclick="loadSearches()">Refresh</button><pre id="searches">—</pre></div><div class="card"><h3>Read search</h3><div class="bar"><input id="searchId" class="grow" placeholder="search id"><input id="soffset" size="8" value="0"><button onclick="readSearch()">Read</button></div><pre id="searchOut">—</pre></div></div></section>
<section id="files" class="panel"><div class="split"><div class="card"><h3>Smart file preview</h3><div class="bar"><input id="filePath" class="grow" placeholder="absolute path"><button onclick="previewFile()">Preview</button></div><div id="fileVisual"></div><pre id="fileOut">—</pre></div><div class="card"><h3>File info</h3><pre id="fileInfo">—</pre></div></div></section>
<section id="history" class="panel"><div class="split"><div class="card"><h3>Recent tool calls</h3><button onclick="loadHistory()">Refresh</button><pre id="historyOut">—</pre></div><div class="card"><h3>Usage</h3><pre id="usageOut">—</pre></div></div></section>
<section id="config" class="panel"><div class="card"><h3>Sanitized configuration</h3><button onclick="loadConfig()">Refresh</button><pre id="configOut">Requires developer/admin scope.</pre></div></section>
<section id="desktop" class="panel"><div class="card"><h3>Unified Desktop Graph</h3><div class="bar"><input id="graphTitle" class="grow" value=".*" placeholder="window title regex"><button onclick="loadGraph()">Build graph</button></div><pre id="graphOut">—</pre></div></section>
<section id="browser" class="panel"><div class="split"><div class="card"><h3>CDP browser targets</h3><button onclick="loadBrowser()">Refresh</button><pre id="browserOut">—</pre></div><div class="card"><h3>Structured browser control</h3><div class="bar"><input id="browserId" class="grow" placeholder="target id"><input id="browserUrl" class="grow" placeholder="https://..."><button onclick="browserNavigate()">Navigate</button><button onclick="browserSnapshot()">Snapshot</button><button onclick="browserScreenshot()">Screenshot</button></div><div class="bar"><input id="browserSelector" class="grow" placeholder="CSS selector"><input id="browserText" class="grow" placeholder="text"><button onclick="browserClick()">Click</button><button onclick="browserType()">Type</button></div><div id="browserVisual"></div><pre id="browserAction">—</pre></div></div></section>
<section id="documents" class="panel"><div class="split"><div class="card"><h3>Document / Office capabilities</h3><button onclick="loadDocCaps()">Refresh</button><pre id="docCaps">—</pre></div><div class="card"><h3>XLSX preview</h3><div class="bar"><input id="xlsxPath" class="grow" placeholder="file.xlsx"><input id="xlsxSheet" placeholder="Sheet1"><input id="xlsxRange" placeholder="A1:D20"><button onclick="xlsxRead()">Read</button></div><pre id="xlsxOut">—</pre></div></div></section>
<section id="runtime" class="panel"><div class="card"><h3>Peers / LLM / Agent runtimes</h3><pre id="runtimeOut">—</pre></div></section>
</main><script>
let timer=null; function H(){return {'Authorization':'Bearer '+token.value,'Content-Type':'application/json'}} async function G(u,o={}){o.headers={...(o.headers||{}),...H()};let r=await fetch(u,o);if(!r.ok)throw new Error(r.status+' '+await r.text());return await r.json()} function esc(s){return String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function tab(id,b){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');b.classList.add('active')}
async function refresh(){try{let [n,j,p,r,t,s,u]=await Promise.all([G('/api/v1/node'),G('/api/v1/jobs'),G('/api/v1/peers'),G('/api/v1/runtime'),G('/api/v1/terminal'),G('/api/v1/searches'),G('/api/v1/usage')]);status.textContent='connected';status.className='green';nodeName.textContent=n.node||'node';nodeMeta.textContent=n.platform||'';running.textContent=j.filter(x=>x.state==='running'||x.state==='queued').length;termCount.textContent=t.filter(x=>!x.closed).length;searchCount.textContent=s.filter(x=>!x.complete).length;peerCount.textContent=Object.keys(p).length;toolCalls.textContent=u.calls||0;runtimeOut.textContent=JSON.stringify({peers:p,...r},null,2);jobRows.innerHTML=j.map(x=>`<tr onclick="pick('${x.id}')"><td><span class="pill">${esc(x.state)}</span></td><td>${esc(x.kind)}</td><td>${esc(x.progress)}% ${esc(x.phase)}</td><td>${esc(x.owner)}</td><td class="mono">${esc(x.id.slice(0,10))}</td></tr>`).join('')}catch(e){status.textContent=e.message;status.className='red'}}
function connect(){sessionStorage.agentnodeToken=token.value;refresh();clearInterval(timer);timer=setInterval(refresh,2500)} function pick(id){jid.value=id;inspectJob()} async function inspectJob(){if(!jid.value)return;try{let [j,e]=await Promise.all([G('/api/v1/jobs/'+jid.value),G('/api/v1/jobs/'+jid.value+'/events')]);jobDetail.textContent=JSON.stringify(j,null,2);events.textContent=JSON.stringify(e.events,null,2)}catch(e){jobDetail.textContent=e.message}} async function cancelJob(){if(!jid.value)return;await G('/api/v1/jobs/'+jid.value+'/cancel',{method:'POST'});await inspectJob();await refresh()}
async function loadTerms(){terms.textContent=JSON.stringify(await G('/api/v1/terminal'),null,2)} async function readTerm(){let r=await G('/api/v1/terminal/'+sid.value+'?cursor='+encodeURIComponent(tcursor.value));termOut.textContent=JSON.stringify(r,null,2);tcursor.value=r.cursor||0} async function loadSearches(){searches.textContent=JSON.stringify(await G('/api/v1/searches'),null,2)} async function readSearch(){searchOut.textContent=JSON.stringify(await G('/api/v1/searches/'+searchId.value+'?offset='+encodeURIComponent(soffset.value)),null,2)}
async function previewFile(){let p=filePath.value;let r=await G('/api/v1/files/read-smart',{method:'POST',body:JSON.stringify({path:p,length:300,include_binary:true})});fileVisual.innerHTML='';if(r.kind==='image'&&r.base64){let im=document.createElement('img');im.src='data:'+r.mime+';base64,'+r.base64;im.style='max-width:100%;max-height:420px;border-radius:8px';fileVisual.appendChild(im);let c={...r};delete c.base64;fileOut.textContent=JSON.stringify(c,null,2)}else{fileOut.textContent=JSON.stringify(r,null,2)}fileInfo.textContent=JSON.stringify(await G('/api/v1/files/info?path='+encodeURIComponent(p)),null,2)} async function loadHistory(){let [h,u]=await Promise.all([G('/api/v1/history?limit=100'),G('/api/v1/usage')]);historyOut.textContent=JSON.stringify(h,null,2);usageOut.textContent=JSON.stringify(u,null,2)} async function loadConfig(){try{configOut.textContent=JSON.stringify(await G('/api/v1/config'),null,2)}catch(e){configOut.textContent=e.message}}
async function loadGraph(){try{graphOut.textContent=JSON.stringify(await G('/api/v1/desktop/graph?title_re='+encodeURIComponent(graphTitle.value)),null,2)}catch(e){graphOut.textContent=e.message}}
async function loadBrowser(){try{browserOut.textContent=JSON.stringify(await G('/api/v1/browser/tabs'),null,2)}catch(e){browserOut.textContent=e.message}}
async function browserNavigate(){try{browserAction.textContent=JSON.stringify(await G('/api/v1/browser/navigate',{method:'POST',body:JSON.stringify({target_id:browserId.value,url:browserUrl.value})}),null,2)}catch(e){browserAction.textContent=e.message}}
async function browserSnapshot(){try{browserAction.textContent=JSON.stringify(await G('/api/v1/browser/'+encodeURIComponent(browserId.value)+'/snapshot'),null,2)}catch(e){browserAction.textContent=e.message}}
async function browserScreenshot(){try{let r=await G('/api/v1/browser/'+encodeURIComponent(browserId.value)+'/screenshot');browserVisual.innerHTML='';if(r.base64){let im=document.createElement('img');im.src='data:image/'+r.format+';base64,'+r.base64;im.style='max-width:100%;max-height:420px;border-radius:8px';browserVisual.appendChild(im)}let c={...r};delete c.base64;browserAction.textContent=JSON.stringify(c,null,2)}catch(e){browserAction.textContent=e.message}}
async function browserClick(){try{browserAction.textContent=JSON.stringify(await G('/api/v1/browser/click',{method:'POST',body:JSON.stringify({target_id:browserId.value,selector:browserSelector.value})}),null,2)}catch(e){browserAction.textContent=e.message}}
async function browserType(){try{browserAction.textContent=JSON.stringify(await G('/api/v1/browser/type',{method:'POST',body:JSON.stringify({target_id:browserId.value,selector:browserSelector.value,text:browserText.value})}),null,2)}catch(e){browserAction.textContent=e.message}}
async function loadDocCaps(){try{let [d,o]=await Promise.all([G('/api/v1/documents/capabilities'),G('/api/v1/office/status')]);docCaps.textContent=JSON.stringify({documents:d,office:o},null,2)}catch(e){docCaps.textContent=e.message}}
async function xlsxRead(){try{xlsxOut.textContent=JSON.stringify(await G('/api/v1/documents/xlsx/read',{method:'POST',body:JSON.stringify({path:xlsxPath.value,sheet:xlsxSheet.value||null,cell_range:xlsxRange.value||null})}),null,2)}catch(e){xlsxOut.textContent=e.message}}
token.value=sessionStorage.agentnodeToken||'';if(token.value)connect();
</script></body></html>'''
