param([string]$AppDir = "C:\ProgramData\AgentNode")
$ErrorActionPreference='SilentlyContinue'
sc.exe stop AgentNode | Out-Null
sc.exe delete AgentNode | Out-Null
schtasks.exe /Delete /TN "AgentNode Desktop Worker" /F | Out-Null
# Derived runtime artifacts (regenerated by the installer). Config and data stay.
Remove-Item "$AppDir\run_core.py","$AppDir\service.env","$AppDir\serve.log" -ErrorAction SilentlyContinue
Write-Host 'Removed services, tasks, and derived runtime artifacts. Configuration and data are retained.'
